baseURL: 'https://blog.wzz.blue'
languageCode: 'zh-cn'
title: 'WZZ'
theme: 'papermod'

params:
  homeInfoParams:
    Title: "随便写写"
    Content: "smallcham"
  socialIcons:
    - name: "github"
      url: "https://github.com/smallcham"
